### ISSUE TITLE
How can I rename the mutations and querys that are generated by default?

### ISSUE THREAD

**Issue by jasp402** [alirizwan/sequelize-graphql-schema#39]
due to internal policies, my tables have an unusual name. I want to rename the queries and mutations that are generated automatically. because it is simpler to rename them or use an alias than to have to create them again.

![image](https://user-images.githubusercontent.com/8978470/72628153-c2018080-391b-11ea-9e61-452f889b475c.png)

Someone will have some idea. I don't think it's an Issue but there is a lack of documentation that addresses these particularities

**Comment by alirizwan** [comment]
Hi it’s better to use alias functionality which is for this same purpose. When defining model level configuration use this:
Model.graphql.alias = {create: “mycreateMutation”, fetch: “mygetquery” } and so on. You have create/edit/delete/fetch options

Sent from my iPhone

On Jan 17, 2020, at 5:24 PM, jasp402 <notifications@github.com> wrote:

﻿

due to internal policies, my tables have an unusual name. I want to rename the queries and mutations that are generated automatically. because it is simpler to rename them or use an alias than to have to create them again.

[image]<https://user-images.githubusercontent.com/8978470/72628153-c2018080-391b-11ea-9e61-452f889b475c.png>

Someone will have some idea. I don't think it's an Issue but there is a lack of documentation that addresses these particularities

**Comment by jasp402** [comment]
![image](https://user-images.githubusercontent.com/8978470/72629917-3db0fc80-391f-11ea-913e-083f7cf9d1f1.png)
God who neglected of me!
Sorry 😭
