### ISSUE TITLE
Does not work with ApolloServer

### ISSUE THREAD

**Issue by optikalefx** [alirizwan/sequelize-graphql-schema#40]
`new ApolloServer({ typeDefs });` takes this typeDefs object. Which expects a `definitions` property.

However when doing

```
const { ApolloServer } = require('apollo-server-koa');
const { GraphQLSchema } = require('graphql');
const db = require('./models');
const typeDefs = new GraphQLSchema(generateSchema(db))
const server = new ApolloServer({ typeDefs, resolvers);
```

We get `TypeError: Cannot read property 'some' of undefined` in `apollo-server-core/src/utils/isDirectiveDefined.ts:16:32` Which is this line

```
typeDef.definitions.some
```

It seems the schema generated by this, doesn't have what normally is present when doing a simple `require('./schema);`

**Comment by alirizwan** [comment]
Generate schema returns both mutations and queries along with resolvers, I’m not sure the way you are trying to use it with Apollo server is correct. I’ll give you an example with Apollo server since I’ve been using it in a similar fashion.

Sent from my iPhone

On Jan 24, 2020, at 5:20 PM, Sean Clark <notifications@github.com> wrote:

﻿

new ApolloServer({ typeDefs }); takes this typeDefs object. Which expects a definitions property.

However when doing

const { ApolloServer } = require('apollo-server-koa');
const { GraphQLSchema } = require('graphql');
const db = require('./models');
const typeDefs = new GraphQLSchema(generateSchema(db))
const server = new ApolloServer({ typeDefs, resolvers);


We get TypeError: Cannot read property 'some' of undefined in apollo-server-core/src/utils/isDirectiveDefined.ts:16:32 Which is this line

typeDef.definitions.some


It seems the schema generated by this, doesn't have what normally is present when doing a simple require('./schema);

**Comment by alirizwan** [comment]
Hi sorry i totally forgot about this :(
here's how I have been using it with apollo server
You shouldn't be providing your resolvers since everything is being generated by the lib itself.

```
const schema = new GraphQLSchema(generateSchema(models));

  server.graphqlLambda((event, context) => ({
    schema,
    context: {
      headers,
      functionName,
      event,
      context,
      models
    }
  }))(event, context, callbackFilter);
